#!/bin/bash

#Written by Colin Vo for Linux Server Project
#This script asks a privelaged user to create a group with an ID.

#Checks if user is root user

if [ $(id -u) -eq 0 ]; then

    #prompt group name
    read -p "Enter a name for the new group: " group

    #checks if group exists
    existingGroup=$(grep -om1 $group /etc/group)

    if [ "$existingGroup" = "$group" ]; then
	     echo "This group exists."; exit 1
    fi

    #prompts group ID
    read -p "Enter a group id for $group: " groupid

    #checks if group id is a number
    if [[ $groupid =~ ^[0-9]*$ ]]; then

    #checks if the group id exists
	  existingId=$(grep -om1 $groupid /etc/group)
	  if [ "$existingId" = "$groupid" ]; then
	     echo "This id exists."; exit 1
	  else
	     #if group id does not exist, add group with id
	     groupadd -g "$groupid" "$group"
	     echo "Group '$group' with id '$groupid' was successfully created. "
	  fi

    else
	     echo "Group id must be a number."; exit 1
    fi

else

       #informs user if they do not have permission
       echo "You do not have permission to perform this action."
       exit 2

fi
